cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'

brew 'ack'
brew 'arping'
brew 'ansible'
brew 'awscli'
brew 'coreutils'
brew 'fasd'
brew 'git'
brew 'git-lfs'
brew 'gnupg'
brew 'mas'
brew 'mercurial'
brew 'node'
brew 'pv'
brew 'python'
brew 'qemu'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'svn'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'zsh'

cask 'xquartz'

#cask '1password'
cask 'adium'
cask 'alfred'
cask 'atom'
cask 'caffeine'
cask 'cord'
cask 'dia'
cask 'firefox'
cask 'flash'
cask 'flux'
cask 'github-desktop'
cask 'google-chrome'
cask 'gpgtools'
cask 'hammerspoon'
cask 'inkscape'
cask 'iterm2'
cask 'libreoffice'
cask 'slack'
cask 'sourcetree'
cask 'the-unarchiver'
cask 'transmission'
cask 'trim-enabler'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
# quicklook plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'

cask 'osxfuse'
cask 'sshfs'
